getwd()
setwd("C:/Users/hml/Documents/R/JHU Exploratory Data Analysis/Week 1")
mydata <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
head(mydata)
subdata <- mydata[mydata$Date %in% c("1/2/2007","2/2/2007") ,]
head(subdata)
gap <- as.numeric(subdata$Global_active_power)
png("plot1.png", width=500, height=500)
hist(gap, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()